# Default config assumes usage of docker
test_harness: 'tf_cnn_bench'
test_environment: 'development-docker'
# System basics
accel_type: 'GTX1080'
platform: 'workstation'
platform_type: 'z420'

# reporting
report_auth: '/service_account_auth_tokens/tensorflow_performance_upload_tb.json'
report_project: 'google.com:tensorflow-performance'
report_dataset: 'benchmark_results_dev'
report_table: 'result'

# tf-cnn-benchmarks
configs: ['foo','foo']